---

# Playbook to create AWS instances, basic playbook to call build script

- hosts: jumpbox
  gather_facts: false
  vars:
    catalog_name: OPENTLC Automation
    item_name: Three Tier Application

# Create AWS instances
  tasks:
  - name: Create 3Tier application AWS instances via supplied scripts
    shell: source ./credential.rc ; ./order_svc.sh -c '{{ catalog_name }}' -i '{{ item_name }}' -t 1 -y
    register: build_log
    ignore_errors: yes

  - name: Debug AWS Build
    debug: 
      var: build_log.stdout
    
